### PR TITLE
Rename docker-compose to compose

### PR DESCRIPTION
**Pull request by iVegas**

### CODE REVIEW

**Comment by csandanov** [comment]
Thank you! Could you please squish all commits in one?

**Comment by iVegas** [comment]
Done

**Comment by iVegas** [comment]
> Hello, what is the reason for renaming docker-compose to compose? Are there any docs or version logs that explain why which change was made? Thank you.

Because we don't need to force newcomers to rely on backward compatibility, which may be dropped in the future.
`docker-compose.yml` is still supported for backward compatibility reasons. See https://docs.docker.com/compose/compose-application-model/#the-compose-file

**Comment by webprogrammierer** [comment]
Okay, good answer.

But the next question is then:
Why did docker rename docker-compose.yml in composeryml?

This will be very confusing for newbies:
In many project folders wie can find the files compser.json, composer.lock, composer.phar ... and now compose.yml.
Many newbies will thing, compose.yml belongs to composer ...

This is not a good idea to remove the "docker-" from docker-compose.yml. 
docker-compose.yml is in any case the more clever option.

**Pull request merged**
