### PR TITLE
Remove unnecessary DRUPAL_VERSION setting

### PR DESCRIPTION
**Pull request by fortis**
Deadcode elimination. Should be applied only with https://github.com/Wodby/drupal-nginx/pull/2

### CODE REVIEW

**Comment by PavelPrischepa** [comment]
We are planned to integrate D6 support. Will it possible in your approach?

**Comment by fortis** [comment]
I have used drupal 6,7,8 with another config, i will do research

**Comment by fortis** [comment]
Oops, my mistake

**Comment by PavelPrischepa** [comment]
Another way is to keep an image per Drupal version: one for D6 and one for D7,8.

**Comment by fortis** [comment]
It looks complicated for multiple project...
Also I have solution in my docker for daily development with multiple projects:

**Nginx drupal.conf**
`
server {
    server_name ~^(?<project>.+)\.local;
    listen 80;

    root /var/www/$project.local;
`

**drupal-compose.yml**
`
  app:
    build: ./php
    links:
      - db
#      - cache
    volumes:
      - ./projects:/var/www
`

**Comment by fortis** [comment]
what you think about using such approach in the future?

**Comment by PavelPrischepa** [comment]
I think we need to keep the project-centric approach. Where the project is the king and has a separate compose file.

But, you are right, it's possibly inconvenient if you hold a lot of projects. Especially, if you need to switch them few times per a day. So, I think we need to design the infrastructure-centric way. There will be a common DB, Nginx for D7 and D8, Nginx for D6, PhpMyAdmin, Solr and other common services. But it most likely to be a new repo, so as not to complicate the current one.

**Comment by PavelPrischepa** [comment]
I'm going to close this PR since there is no activity.

**Pull request closed without merging**
