### PR TITLE
Add PHP_XDEBUG_REMOTE_LOG to let users verify XDEBUG.

### PR DESCRIPTION
**Pull request by clemens-tolboom**
Trying to help with #345 it is quite handy to have the xdebug log file at hand.

### CODE REVIEW

**Comment by PavelPrischepa** [comment]
Thank you @clemens-tolboom, I've added `xdebug.remove_log` as debug option to documentation https://wodby.com/docs/stacks/drupal/containers/#xdebug-troubleshooting.

**Comment by clemens-tolboom** [comment]
Why not add this PR to the code?!? It probably helps people earlier in the 'debug' process.

**Comment by PavelPrischepa** [comment]
@clemens-tolboom agree it makes sense.

**Comment by clemens-tolboom** [comment]
:-)

**Pull request merged**
