### PR TITLE
Add setfacl solution as fix for permission problems.

### PR DESCRIPTION
**Pull request by jsobiecki**
Hi Guys,

Thanks for your hard work!. I have minor update for docs.  

Information from permission section (assign user to "fake" group with id 82) didn't fixed all my problems related to permissions. After some experiments, I decided to use setfacl tool.
This approach is inspired by http://symfony.com/doc/current/setup/file_permissions.html

### CODE REVIEW

**Comment by csandanov** [comment]
@PavelPrischepa @hrdcdr guys, can you try it out on Linux

**Comment by jsobiecki** [comment]
I'm wondering, if slight change wouldn't be better, instead of single permission mask
"-m u:$(whoami):rwX", to use three masks

"-m u:$(whoami):rwX -m -m u:82:rwX -m u:101:rX"  
(101 is user from container), 82 is for user in php container.

Let me know what do you think.

**Comment by MatthieuScarset** [comment]
Sounds like a better id that adding our user to GID 82 @jsobiecki 
could you please explain how you did step by step to fix permissions? 
Thanks!

**Comment by jsobiecki** [comment]
@MatthieuScarset 

Step by step is something like this:
```
cd project_path
sudo setfacl -dR -m u:$(whoami):rwX -m u:21:rX -m u:82:rwX  path_to_shared_volume
sudo setfacl -R -m u:$(whoami):rwX -m u:21:rX -m u:82:rwX  path_to_shared_volume
```
First setfacl execution sets defaults for all newly created dirs and files.
Second one actually changes ACL settings for all files.

**Comment by PavelPrischepa** [comment]
@jsobiecki thank you for the suggestion.

I think we should provide some info about how to setup acl, because it doesn't enabled by default in some OS.

**Ubuntu**
It enabled by default in Ubuntu since 14.04 + ext4 fs. Otherwise you should follow the manual https://help.ubuntu.com/community/FilePermissionsACLs#Enabling_ACLs_in_the_Filesystem.

**Comment by jsobiecki** [comment]
Hi @PavelPrischepa - I added small paragraph about setting up ACL to my PR. What do you think?

**Comment by PavelPrischepa** [comment]
@jsobiecki merged, thanks for the contribution!

**Pull request merged**
