### PR TITLE
Adding .env, and other changes

### PR DESCRIPTION
**Pull request by waspper**
Hello guys.

Nice work. A very-complete set of docker images.

Inspecting a bit, I think/propose this PR. A short explanation about changes:

1. **File "docker-compose.yml" renamed to "docker-compose.yml.default":** Includes configurable variables from a .env file, where it should be easier and cleaner to change/manage several values. This ".env" file is created by copying the .env.default, and added to the .gitignore to allow end-user having its own, without losing the upstream version.

2. **Makefile**: Includes several commands by default. Same as previous point: A default one (Makefile) is provided with just creating another to place there user customizations.

3. **.env.default**: File where setting may be configured/stored.

### CODE REVIEW

**Comment by csandanov** [comment]
Thanks!

* I'm all for using `.env` file but the way you moved out only image name and a version is kinda weird. You either move repo + image so people understand that it's actually an image or you just move version and stability tag. I mean, do you really need `MARIADB_IMAGE=mariadb:10.2-3.0.2` when you can have `MARIADB_IMAGE=10.2-3.0.2`, I would probably even separate them to: 
```
MARIADB_VER=10.2
# MARIADB_VER=10.1
MARIADB_TAG=3.0.2
```
so in compose file you'll have:
```yml
mariadb
    image: wodby/mariadb:${MARIADB_VER}-${MARIADB_TAG}
```

* We should not mix docker4drupal's Makefile and boilerplate for aliases. I suggest we keep the original Makefile and add `boilerplate.mk` for aliases (included in Makefile) that people will either rename to Makefile or include. No need to have `default_` prefix for targets, it should be short and simple by default. The filename kinda suggests you can change things. Also, it's weird that `init` has down, do we really need this target?

* What's the point of having `front` network? Why is it called `front`?

* I don't think renaming to `docker-compose.yml.default` makes a lot of sense. It's not like people will use two compose files. And with `.env` file it will change very rarely.

**Comment by waspper** [comment]
Hello @csandanov. Thanks for suggestions. Some comments about your points:
1. I was thinking something like that. But then I saw (when doing it for PHP) that pattern not always the same. For example: For MariaDB works "wodby/mariadb:${MARIADB_IMAGE}"  or as you say, "wodby/mariadb:${MARIADB_VER}-${MARIADB_TAG}". But for PHP thinks are different, because we have as options: "drupal:VERSION" or "drupal-php:VERSION". So, in docker-compose.yml we should have an extra variable to know if vanilla Drupal, or just PHP for Drupal. At the end, it will introduce more variables into the .env. Then, if launched something like "wodby/mariadb-drupal:VERSION" at same time with "mariadb:VERSION", will make it more difficult to manage. That's the reaso I proposed to just keep it into a single variable :)

2. The "Makefile.override" (copied on the fly from Makefile.override.default) version provided is for allowing user to keep current target rules or edit them (or even add more) as needed without "changing" the upstream version. This allow, for example, a "git pull" for updates without loosing previous custom changes, witch will allow to inspect/compare new version with current one. Same applies to the docker-compose.yml.default: This is not used. The "real one" used is "docker-compose.yml", which is copied/created on the fly. But you're right. Maybe naming needs improvement. I'm not sure to understand what you mean with add a boilerplate.mk and include it or rename it. What I'ld like to propose is keeping the default Makefile allowing "secure pulls" (not overriding user changes). 

PS: Sure. You're right with removing "default_" from target rules.

3. For example, at this PR by executing "make default_info" will show us assigned IPs, which maybe useful for quick-testing and/or easy debugging. Also, you watch the project into the web browser by just going to the IP given by that network.

4. It will be the "default-base file" that default "docker-compose.yml" will be copied from. Only this last will be used (or if another different added to the .env, it is possible, too). But this point is related to the previous 1: Keep changes from user and upstream.

**Comment by csandanov** [comment]
> For example, at this PR by executing "make default_info" will show us assigned IPs, which maybe useful for quick-testing and/or easy debugging. Also, you watch the project into the web browser by just going to the IP given by that network.

This "maybe useful" doesn't sound convincing to complicate things. Perhaps if you give me an example use case when it's super useful I will change my mind. Don't forget we have traefik to access everything you need in a browser. I highly appreciate your efforts but we should keep things as simple as possible, and we shouldn't cover specific cases, folks can always customize everything to their needs.

**Comment by csandanov** [comment]
Thank you for your input, your suggestion have been accepted in most part, please see https://github.com/wodby/docker4drupal/releases/tag/5.0.0 and referenced commits.

**Pull request closed without merging**
