### PR TITLE
Replace docker-sync with Mutagen

### LINKED ISSUE #442: Use Mutagen instead of docker-sync
It's a known issue that Docker for Mac is slow when using shared volumes containing a big amount of files, see the historical https://github.com/docker/for-mac/issues/77.

So, some workarounds came like [`:cached` ](https://docs.docker.com/docker-for-mac/osxfs-caching/#cached) and [docker-sync](http://docker-sync.io/). However it's not totally satisfactory because it's still slow compared to native and docker-sync requires a lot of resources when syncing. 

That being said, there is a good alternative, almost perfect, which is [Mutagen](https://mutagen.io/). Some benchmark is available [here](https://medium.com/netresearch/improving-performance-for-docker-on-mac-computers-when-using-named-volumes-55580efcbf68#bf1b). It's almost **as fast as native** shared volumes with Linux!

So, I suggest replacing docker-sync with Mutagen. I'm gonna send a pull request with Mutagen configured for docker4drupal.

### PR DESCRIPTION
**Pull request by Kwadz**
Fixes #442

### CODE REVIEW

**Comment by csandanov** [comment]
How to use this? `mutagen sync create`? what's the Dockerfile for?

**Comment by Kwadz** [comment]
You can start the sync with `mutagen project start`. About the Dockerfile it's made to create an empty mutagen service that sits idle and serves as the hosting point for mutagen-agent processes (which provide code synchronization and network forwarding). The reason for this mutagen service is two-fold:

- It allows the same agent binary to be re-used, thus only requiring a single agent copy.
- It allows the mutagen service to be started before other services so that initial synchronization can take place before other services start. This may be necessary if those services' entry points expect code to already be available in the target locations.

**Comment by csandanov** [comment]
Ok, could you please resolve conflict and I proceed with the merge

**Comment by michalkleiner** [comment]
Mutagen can also integrate with Docker Compose, more precisely replace it... and then all the config can go into the docker-compose.yml file.
See https://mutagen.io/documentation/orchestration/compose

**Pull request merged**
